### ISSUE TITLE
netcdfcpp.h missing from repo?

### ISSUE THREAD

**Issue by taobrienlbl** [ClimateGlobalChange/tempestremap#2]
On pulling down a fresh clone of tempestremap and attempting to build on my macbook, I get the following error:

```
g++ -O3 -I/usr/local/include -c -o build/GenerateRLLMesh.o GenerateRLLMesh.cpp
GenerateRLLMesh.cpp:24:10: fatal error: 'netcdfcpp.h' file not found
#include "netcdfcpp.h"
         ^
1 error generated.
```

Perhaps netcdfcpp.h didn't get added to the repo?

**Comment by alexfight** [comment]
Hi:
   I just met the same problem above. And I am totally a novice of C++. Would you mind tell me how to check the makefile? because I didn't find makefile in the directory. 

Thanks!

**Comment by paullric** [comment]
Hi alexfight,

Try the following command sequence:

bash
wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-cxx-4.2.tar.gz
tar -xzf netcdf-cxx-4.2.tar.gz 
cd netcdf-cxx-4.2
export CPPFLAGS="-I<path-to-netcdf>/include"
export LDFLAGS="-L<path-to-netcdf>/lib"
./configure --prefix="$HOME/netcdf-cxx"
make all
make install

Then edit tempestremap/mk/system.make in order to determine which system/*.make will be called.  Edit the appropriate tempestremap/mk/system/*.make file to add:

NETCDF_CXXFLAGS=   -I$(NETCDF_ROOT)/include -I$(HOME)/netcdf-cxx/include
NETCDF_LDFLAGS=    -L$(NETCDF_ROOT)/lib -L$(HOME)/netcdf-cxx/lib

Apologies for the complexity.  We're working on building a cmake file for the library.

**Comment by alexfight** [comment]
Hi Paullric:
    Thank you so much for providing the method for my problem. 
    I have finished all steps except for the last one"edit tempestremap/mk/system.make". I have no idea where this file is. I searched my computer, but Finder under **searching**  for a long time and it seems that it can not find the file.
   would you tell me how to conduct the last step in detail?

Alex

**Comment by paullric** [comment]
Hi alexfight,

Have you updated to the latest commit?  You’ll notice it appears here:

https://github.com/ClimateGlobalChange/tempestremap/tree/master/mk <https://github.com/ClimateGlobalChange/tempestremap/tree/master/mk>

~ Paul

**Comment by alexfight** [comment]
Hi Paul:
     Thank you for your patience.
     I am not familiar with github, I just use it to find methods for my computer issues. To be honest, I can't understand what you was talking. I just copy them. Sorry about that.
    I am learning it. It will take some time. 
    Anyway, thank you very much. 

Sincerely
Alex

**Comment by bwtimmermans** [comment]
Hi Paul,

Possibly relevant here (I was searching a similar problem for a different code), the file "netcdfcpp.h" seems to be obselete and ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-cxx-4.2.tar.gz is not directly linked as part of the current NetCDF distribution. netcdf-cxx4-4.3.0.tar.gz does not contain "netcdfcpp.h"

Should a different header file be referenced?

This is also relevant because I do not believe "netcdfcpp.h" is maintained on any NERSC platform. (And I am probably interested in using your code at some point - when I find time).

Ben

**Comment by paullric** [comment]
Hi Ben,

Yes, this has been an outstanding issue for some time.  The code was written with the legacy netcdf-cxx-4.2 interfaces and reorganizing the code to support the newest interfaces for NetCDF will likely take some effort.  I don’t think there’s any significant performance gain with the latest C++ interfaces, since they’re a thin veneer over the C library.  It may simply be easier to distribute the netcdfcpp.h interfaces with our code.

I’ve had no issue compiling netcdf-cxx-4.2 on Cori, even when pointing it at the newest NetCDF C libraries.

~ Paul

**Comment by rfvander** [comment]
Hi Paul,
I repeated the steps you explained in your note from December 15. All works well, until I get to the configure command. The end of the output is this:
checking how to hardcode library paths into programs... immediate
configure: finding other utilities
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking netcdf.h usability... no
checking netcdf.h presence... no
checking for netcdf.h... no
configure: error: netcdf.h could not be found. Please set CPPFLAGS.
I did set CPPFLAGS according to your instructions, but there is no include directory in the NETCDF repo I obtained. I reckon it is supposed to get created. Can you give any advice how to proceed? Thanks!

Rob
