### ISSUE TITLE
Help building Tempest2 on Mac

### ISSUE THREAD

**Issue by czender** [ClimateGlobalChange/tempestremap#35]
Hi Tempest gurus,

I have tried unsuccessfully to install Tempest2 on my MacBookPro (though no problems building Tempest2 on Linux). I use MacPorts, which successfully builds Tempest1. I hope you can give me some suggestions for Tempest2, where the configure command never successfully completes. Currently it dies because it can't find Fortran.

Basic setup:
```
sudo port install netcdf-cxx
cd ${DATA}/tmp/tempestremap
git pull
autoreconf -fi
mkdir -p build
cd ${DATA}/tmp/tempestremap/build
../configure --prefix=/usr/local --with-blas=/opt/local --with-lapack=/opt/local --with-netcdf=/opt/local --with-hdf5=/opt/local

```
Does this look good so far? In any case, configure fails with

```
...
checking if g++ supports C++0x features with -std=gnu++0x... yes
checking for ifort... no
checking for gfortran... no
checking for g77... no
checking for f77... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking how to get verbose linking output from ... configure: WARNING: compilation failed

checking for Fortran 77 libraries of ... 
checking for sgemm_ in /opt/local... no
checking for sgemm_... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... yes
checking for dgemm_ in -ldgemm... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -lmkl_core... no
checking for sgemm_... (cached) no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) yes
checking for sgemm_ in -lessl... no
checking for sgemm_ in -lblas... (cached) yes
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... configure: error: in `/Users/zender/data/tmp/tempestremap/build':
configure: error: cannot compile a simple Fortran program
See `config.log' for more details
```
Tempest1 never cared about Fortran. Fortran is weird on Macs. Is it really necessary for Tempest2? How do you install gfortran?

**Comment by paullric** [comment]
Pinging @vijaysm who authored the autoreconf build system.

Tempest2 should not care about Fortran.  I was under the impression that the Fortran checks were disabled in the latest build system.

**Comment by czender** [comment]
Thanks. It worked once I managed to point the system to gfortran with
```
port select --list gcc
sudo port select --set gcc mp-gcc7
```
Will leave this issue open as I think the Fortran checks in `configure` should be disabled unless Fortran is actually used. Most Mac users will not have a fortran compiler by default.

**Comment by vijaysm** [comment]
I thought I had removed the dependencies on Fortran before. Nevertheless,
the problem is Fortran name mangling becomes mandatory for BLAS/LAPACK
calls. Paul assumes throughout in the code that the symbols have lower case
with underscore. While this is standard in GNU, it may be quite different
as you move to different compilers (Intel, PGI, XLF) necessary for ACME.

We can't account for this unless we find the symbol format during
configure. Hence the restriction. Anyway I recently solved a similar issue
in MOAB and will take a look to see if we can do the same in Tempest.

Vijay

**Comment by paullric** [comment]
The problem is that BLAS/LAPACK calls often differ between libraries beyond simple name mangling issues.  I know that MKL, ACML and ESSL actually have very different interfaces for these calls (sometimes info is passed as a pointer, sometimes it’s the return value from the function).  This has been a persistent problem arising from the lack of standardization of LAPACK.  I’m thinking it would be better to have a LinearAlgebra.h header that provides a uniform interface to the LAPACK calls.

~ Paul

**Comment by paullric** [comment]
Hi Charlie - just realizing this issue is still open.  Can you verify it's working now?

**Comment by czender** [comment]
I can compile TR on Macs. I'm not sure whether it would work without a fortran compiler. Fine by me to close this issue.

**Comment by paullric** [comment]
All the fortran dependencies should have now been removed.  I think Vijay finally confirmed that is the case.
