### ISSUE TITLE
Option to interchange lat/lon order

### ISSUE THREAD

**Issue by mmundt** [ClimateGlobalChange/tempestremap#7]
It would be nice to have a command-line argument which allows the user to swap the print-out order of lat and lon (for generating maps).

**Comment by mt5555** [comment]
Is this is reference to the src_grid_dims() and dst_grid_dims() arrays in the mapping file?   In which case I would recommend tempestremap should switch so the default matches the SCRIP convention

**Comment by czender** [comment]
Yes, I first expected the SCRIP convention and then coded a test to work around the unexpected Tempest behavior. I think ncks will work on new and old Tempest files if Tempest switches to the SCRIP convention.

**Comment by mt5555** [comment]
resolved with
https://github.com/ClimateGlobalChange/tempestremap/commit/002d16104ff65da9e39ab7a0cbeab32bbaa882b4

**Comment by czender** [comment]
NCO now patched to work with older and newer Tempest lon/lat orders. The patch relies on contents of "name0" attribute of src/dst_grid_dims to indicate when the _old_ ordering should be followed. Otherwise ncks assumes the newer ordering. Are there even older Tempest mapfiles that do not have the "name0" attribute? If so NCO will break on those, but otherwise looks good for all recent versions of Tempest.

**Comment by paullric** [comment]
Hi Charlie,

I’m not even sure if there are older TempestRemap maps that have name0/name1 (it doesn’t really have a large user base at the moment).

Thanks!

~ Paul
